### ISSUE TITLE
Dendrogram show_diameters=True should have an option of how to interpret starting section radius

### ISSUE THREAD

**Issue by mgeplf** [BlueBrain/NeuroM#654] opened 2017-09-28 13:31 UTC
@wvangeit suggests adding a feature to the dendrogram plotting so that one can toggle what the 'first' diameter of a section is: whether it's the last one of the previous section or whether that is skipped.

Currently, the previous section's diameter is used, which means that (usually) there is a cone as the first segment of the dendrogram, yet this might not be how the simulator interprets the data, and thus it can be confusing.

**Comment by mgeplf** [comment] 2017-09-28 14:49
So, after discussing this a bit w/ @wizmer, I'm thinking that maybe this should be an option when loading the morphology: that way the dendrogram will be 'correct', but also any other calculation that's made (area, volume, etc).

In NEURON, for instance, the diameter of the first point is set to that of the second point, at least in the (old) neurolucida reader:
https://github.com/nrnhines/nrn/blob/master/share/lib/hoc/import3d/read_nlcda.hoc#L51

**Comment by mgeplf** [comment] 2017-09-28 15:00
Quick pic: (green is original segment, cyan and salmon are its children)
On the left is if the parent's diameter is chosen, on the right if the child's second point is used.
![morph_diam](https://user-images.githubusercontent.com/13150119/30973907-949216ee-a46e-11e7-8b62-77c0f0e0ceaf.png)

**Comment by lidakanari** [comment] 2017-09-28 15:11
Thanks for the illustration because the discussion was confusing :) From the anatomical point of view the right one is the "standard". So since NeuroM is concerned about the morphologies it is definitely important to keep this - at least as an option. This is indeed more important for the computation of diameters, volumes etc and this certainly needs to reflect the right definition to be consistent with other tools. However, you need to make sure that duplicate points are not removed in the internal NeuroM representation during loading -especially since swc and ascii data do not contain duplicate points- . In previous versions the first duplicate point of each section was removed and the area - volume results were double checked with Neuromorpho.org data and were accurately computed.

**Comment by wvangeit** [comment] 2017-09-28 15:42
I don't understand the last sentence. So in earlier versions the duplicate point was removed, and it gave results that matched neuromorpho ? Does that mean neuromorpho uses the left plot to calculate the surface areas ?

**Comment by lidakanari** [comment] 2017-09-28 15:46
In neuromorpho the data used are either in swc or in asc. Both of those formats do not have duplicate points -so by default this is the right version-, so I am assuming that neuromorpho used the right (right? I am also confused :) plot.

**Comment by wizmer** [comment] 2017-09-28 16:06
At least in the swc format the representation on the right is probably not what we have right now in NeuroM. As an example:
```
# id, type, x, y, z, r, p
  1 1  0  0 0 1. -1
  2 3  1  0 0 2.  1
```

Which is one soma, one dendrite with a single segment.
if you compute the length of the neurite `neuron.neurites[0].length` you get 0 instead of 1.
To have the correct representation (right plot), we need to internally duplicate the neurite parent while keeping the child radius.

```
# id, type, x, y, z, r, p
  1 1 0 0 0 1. -1
  2 3 0 0 0 2. 1 <-- line 1 duplicated, type changed 1->3, radius changed 1.->2.
  3 3 1 0 0 2. 2 <- id is now 3
```
Now you get a length of 2 and a volume of 12.56

**Comment by lidakanari** [comment] 2017-09-28 17:26
I think this is at the first point of the tree that is connected to the soma (*so the definition of the duplicate points here are a bit blurry). I would suggest to create an example that has a tree with three sections. Something like the following will do:

```
# id, type, x, y, z, r, p
  1 1  0  0 0 1. -1
  2 3  1  0 0 2.  1
  3 3  1  1 0 2.  2
  4 3  1 -1 0.2   2
```

This way we can get a better idea of the behavior at the beginning of section / bifurcation.

**Comment by wizmer** [comment] 2017-09-29 07:57
Ah ineed, things are a bit different now.
@lidakanari , I took you example and tweaked it a bit for having differents radii for each section.
```
# id, type, x, y, z, r, p
  1 1  0  0 0 3. -1
  2 3  1  0 0 2.  1
  3 3  1  1 0 1.  2
  4 3  1 -1 0 1.  2
```
In the end sections we have the following numbers:
length: 1.0
volume: 7.330382858376184
points section 3 (XYZR): [[ 1.  0.  0.  2.], [ 1.  1.  0.  1.]]
points section 4 (XYZR): [[ 1.  0.  0.  2.], [ 1. -1.  0.  1.]]

So yeah, the point with id 2 is now duplicated correctly into each of the child sections. However it still has a radius of 2. To match the "correct" representation, it should have a radius of 1.

**Comment by lidakanari** [comment] 2017-09-29 09:01
Perfect. That makes sense. 

I am testing the following cell against its neuromorpho.org morphometrics: 
http://neuromorpho.org/neuron_info.jsp?neuron_name=dhDSCT-Cell-h 

Here are the results: 
```
Soma Surface : | 3663.72 (neuromorpho) | 3663.72 (NeuroM)
-- | --
Average Diameter : | 2.59 (neuromorpho) | 2.58 (NeuroM)
-- | --
Total Length : | 5064.1 (neuromorpho) | 4915.6 (NeuroM)
-- | --
Total Surface : | 46547.9 (neuromorpho) | 40873.6 (NeuroM)
-- | --
Total Volume : | 86699.4 (neuromorpho) | 47504.4 (NeuroM)
```

So, obviously there is an inconsistency... This is quite peculiar, but we need to check this (maybe we should create a new issue related to the current one?)! I used the swc and the latest NeuroM version for this.

**Comment by wvangeit** [comment] 2017-09-29 09:08
Is neuromorpho using L-measure to get these values. Is the source code of l-measure available somewhere ?

**Comment by jdcourcol** [comment] 2017-09-29 09:10
https://github.com/spolavar/L-Measure

**Comment by lidakanari** [comment] 2017-09-29 09:10
Yes, L-measure is available online (http://cng.gmu.edu:8080/Lm/). I am not sure if L-measure is used for the neuromorpho measurements, but that is my impression.

**Comment by wvangeit** [comment] 2017-09-29 09:29
It seems they are calculate a cylinder surface, not a frustum:
https://github.com/spolavar/L-Measure/blob/5efef47372b43fdcd003e34da0c80986ba784ccf/Func.h#L1331

It that sense they don't have our problem, because they don't consider the diameter of the previous fragment.

**Comment by lidakanari** [comment] 2017-09-29 09:39
Ah, that would explain the inconsistencies! Thanks for looking into this @wvangeit !

**Comment by wizmer** [comment] 2017-09-29 10:15
But, but, but... do you think that explains also the huge inconsistancy on the volume ??

**Comment by wvangeit** [comment] 2017-09-29 10:36
Well, the volume is calculated in the same way as the surface, not based on the diameter of the previous section (I assume NeuroM uses the frustum volume ?):

https://github.com/spolavar/L-Measure/blob/5efef47372b43fdcd003e34da0c80986ba784ccf/Func.h#L1380

**Comment by lidakanari** [comment] 2017-09-29 11:00
Hm, I am not sure that this explains everything... I have the impression that the differences between the volume measurements should not be that big even with the different methods of the computation; it is almost doubled...

**Comment by wvangeit** [comment] 2017-09-29 11:53
Yes, sure. I only pointed out this difference. But there can be other ones :-)

**Comment by wvangeit** [comment] 2017-09-29 12:06
NEURON seems to be closer to the neuromorpho value.
I loaded the swc file:
NEURON area:  44539.131  um2
NEURON volume: 77527.804  um3

**Comment by wvangeit** [comment] 2017-09-29 13:22
@lidakanari did you include the soma in your calculation ? That's around 20k volume.

**Comment by lidakanari** [comment] 2017-09-29 13:29
@wvangeit No, good point! This was the section_volumes summed up. Is the soma area / volume included in L-measure / neuromorpho and Neuron? 

For the total areas I double checked the sum of the section_areas and the total_area and the two measurements agreed. Now, if we add the soma_area the Total cell area is: 44537.34 which is much closer to the neuromorpho value (and pretty close to the Neuron you just send). 

About the soma volume, it is unfortunately not currently implemented in NeuroM.

**Comment by wvangeit** [comment] 2017-09-29 14:10
Not completely sure about L-measure, but Neuron definitely includes the soma.

Probably a function should be added to neurom to calculate the total surface / volume of an entire neuron

**Comment by asanin-epfl** [comment] 2021-05-10 11:30
Closing as obsolete now. Anyway having `show_diameters=True` for dendrogram was a solution for symptoms rather than the cause. The problem was in interpretation of sections. Currently the first section point is used for plotting.

**Closed by asanin-epfl** 2021-05-10 11:30 UTC
Labels: new feature
