### ISSUE TITLE
v2: how to deal w/ unifurcations when MorphIO is the reader

### ISSUE THREAD

**Issue by mgeplf** [BlueBrain/NeuroM#872] opened 2021-03-02 13:58 UTC
Once https://github.com/BlueBrain/MorphIO/issues/235 happens, we will have to decide how to handle unifurcations, and specifically the features like `strahler_order`, `strahler_order`, etc; these will be impacted by having a section that does not bifurcate, thereby impacting the individual values for a section, and the statistics for a full morphology.

If unifurcations are merged, it's impossible to match `section_ids` from a circuit to the individual section's value of the feature.
If they aren't merged, the global statics (ie: mean/stddev, etc) will not be what is expected if the user believes that unifurcations don't exist.

Thus, it's not clear which to pick as the default, and which to give warnings or do automatically.  Figuring that out is what this ticket is for.

**Comment by arnaudon** [comment] 2021-03-02 14:12
One option could be that unifurcations are ignored in relevant features, by simply adding an `if len(section.children) > 1` or something like that in the code.

**Comment by mgeplf** [comment] 2021-03-02 14:17
> One option could be that unifurcations are ignored in relevant features

Interesting, I hadn't even considered that; but it may make the most intuitive sense.
Hearing from other morphometricians would be helpful, at some point.

You also raised the point about emitting a warning; I think that is another good avenue to consider in `NeuroM`, where such warning can be more targetted.

**Comment by eleftherioszisis** [comment] 2021-03-02 14:18
If NeuroM strictly expects a binary tree, then this check/conversion must take place at loading. Do we know which features assume a binary tree and which not?

**Comment by arnaudon** [comment] 2021-03-02 14:20
We should carefully check/test that I think when the time comes. We can devote some times in our team to do that once we have new morphio version and neurom v2.

**Comment by eleftherioszisis** [comment] 2021-03-02 14:23
We will need to keep track of which features work with uni/bif. Given that NeuroM was designed for binary trees, does checking on the feature level bring anything to the table? Are there features that are meaningful for unifurcations?

**Comment by wizmer** [comment] 2021-03-02 15:12
> and specifically the features like strahler_order, strahler_order

`strahler_order` and such are obvious because they deal with children but basically all features starting by `section_*` will be impacted starting at the most trivial ones such as `section_length`. 

For this reason, using the manual check `if len(section.children) > 1` would need to be added almost everywhere where we iterate on sections. We would end up creating an alternative method that does it for us by replacing the use of `iter_section` by the alternative new method `iter_section_sanitized`. Most probably the use of the old method `iter_sections` would fall to zero (correct me if I'm wrong but I don't see in NeuroM where we explicitely would like to not merge sections).

Ultimately this is equivalent to sanitizing the morph at loading time and to keep the existing `iter_sections`

> Are there features that are meaningful for unifurcations?

Finding one would be the only reason to go for the manual check (or equivalently, to the implementation of a new method `iter_sections_sanitized`).

**Comment by arnaudon** [comment] 2021-03-02 17:56
or just a check upon loading a morph to see if any unifurcation are present, and print a big warning saying it won't work on some features, and how to sanitize the morphology.

**Comment by asanin-epfl** [comment] 2021-03-08 14:25
From what I understood, the current policy of NeuroM is to sanitize on load. So, we just need to keep it.
```
("CellBody"
(CellBody)
(1 1 0 1 S1)
(-1 1 0 1 S2)
(-1 -1 0 2 S3)
)

((Dendrite)
 (0 0 1 1)
 (0 0 2 1)
 (
   (0 0 2 1)
   (0 0 3 1)
 )
)
```

```python
import neurom as nm

nrn = nm.load_neuron('unifurcation.asc')
print(nm.features.get('section_lengths', nrn))
# [2.]
print(nm.features.get('segment_lengths', nrn))
# [1. 0. 1.]
```

**Comment by arnaudon** [comment] 2021-03-26 10:09
By default upon loading, the call to morphio removes unifurcations is made, so I think this discussion can be closed.

**Comment by asanin-epfl** [comment] 2021-04-29 13:26
unifurcations are not cleaned on Morphology load/read in NeuroM v2. Here is the final comment of the discussion about it https://github.com/BlueBrain/NeuroM/pull/755#issuecomment-814768966.

**Comment by asanin-epfl** [comment] 2021-05-07 08:46
Closing via #911. Unifurcations are not removed on load. This case is explicitly described now in docs at the page "Migration to v2".

**Closed by asanin-epfl** 2021-05-07 08:46 UTC
Labels: version 2.0
