### ISSUE TITLE
Plot in existing figure/axis

### ISSUE THREAD

**Issue by INF-Rene** [BlueBrain/NeuroM#766] opened 2019-08-16 13:56 UTC
I noticed that `viewer.draw(nrn) `creates a new figure and plots the neuron on that axis. As far as I can find in the docs there is no way to tell the method which axis to plot on, such as` viewer.draw(nrn, ax=ax)
`
This is quite crucial for generating neuron galleries, which are often seen in publications and supplementary data.

Or am I missing something?

**Comment by wizmer** [comment] 2019-08-19 07:43
Hi @INF-Rene !

Have a look at https://neurom.readthedocs.io/en/latest/_neurom_build/neurom.view.view.html#module-neurom.view.view
I think `plot_neuron` and `plot_neuron3d` are what you need.

**Comment by wizmer** [comment] 2019-08-19 08:47
@mgeplf Should we pass this part of the doc in the public documentation ?

**Comment by INF-Rene** [comment] 2019-08-19 09:08
Hey, @wizmer, thanks for the help!

Actually I already tried that function, but all it does for me is just change the title of the plot to the filename, while not plotting anything. `viewer.draw(nrn)` works fine on the same nrn object

**Comment by wizmer** [comment] 2019-08-19 12:54
Hum, that should work. You have to pass your own axes as the first argument and the neuron as the 2nd one.
Here is a small example:
```
import matplotlib.pyplot as plt
from neurom.view.view import plot_neuron
plt.figure()                                                                                                                                                                                        
ax = plt.gca()
plot_neuron(ax, neuron)
```
What exactly did you try ?

**Comment by INF-Rene** [comment] 2019-08-19 13:06
Sorry, just found out that it was just a scaling issue. Apparantly the `plot_neuron` method does not automatically set the scaling of the axes correctly. A simple `ax.autoscale()` fixed it.

**Comment by wizmer** [comment] 2019-08-19 13:33
Cool. Yes, `plot_neuron` does not mutate the axes, by design.
Closing the ticket.

**Closed by wizmer** 2019-08-19 13:33 UTC
