### ISSUE TITLE
Error while reading SWC from SEU

### ISSUE THREAD

**Issue by jonathanlurie** [BlueBrain/NeuroM#858] opened 2020-12-02 15:11 UTC
Hello,
thanks to the collaboration with have with South East University, we have quite a lot of morphologies, all created by Vaad 3D. Out of the 200 we recently got, 199 are not readable and as far as I have tested, it's always the same error:
```
Traceback (most recent call last):
  File "/Users/lurie/opt/miniconda3/lib/python3.8/site-packages/neurom/io/utils.py", line 193, in load_data
    return _READERS[reader](filename)
  File "/Users/lurie/opt/miniconda3/lib/python3.8/site-packages/neurom/io/swc.py", line 56, in read
    return data_wrapper(data[:, [X, Y, Z, R, TYPE, ID, P]], 'SWC', None)
  File "/Users/lurie/opt/miniconda3/lib/python3.8/site-packages/neurom/io/datawrapper.py", line 74, in __init__
    self.sections = sections if sections is not None else _extract_sections(data_block)
  File "/Users/lurie/opt/miniconda3/lib/python3.8/site-packages/neurom/io/datawrapper.py", line 206, in _extract_sections
    sec.pid = parent_section[sec.ids[0]]
KeyError: 108

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_neurom.py", line 6, in <module>
    nrn = nm.load_neuron(morph_path)
  File "/Users/lurie/opt/miniconda3/lib/python3.8/site-packages/neurom/io/utils.py", line 116, in load_neuron
    rdw = load_data(handle, reader)
  File "/Users/lurie/opt/miniconda3/lib/python3.8/site-packages/neurom/io/utils.py", line 196, in load_data
    raise RawDataError('Error reading file %s:\n%s' % (filename, str(e))) from e
neurom.exceptions.RawDataError: Error reading file /Volumes/LaCie/BBP/morphologies/SEU_october2020/swc/17302/17302-Z2991-X7767-Y3860.swc:
108
```

The error is triggered [here](https://github.com/BlueBrain/NeuroM/blob/master/neurom/io/datawrapper.py#L205).

My gut feeling is that this error is caused by the order the points are declared in the swc file. The parent nodes are not especially declared first, so most of the time, a point will refer to its parent by an id that is actually later in the file. That's really just a gut feeling though.

In parallel, I will send you a file sample by email.

Best.

**Comment by mgeplf** [comment] 2020-12-02 15:25
Thanks for the report.  We have a test filethat checks if the order matters in SWC:
https://github.com/BlueBrain/NeuroM/blob/master/test_data/swc/simple_reversed.swc

So we'll have to investigate this.

**Comment by mgeplf** [comment] 2020-12-02 15:40
I should note that NEURON version '8.0.dev-193-gfc74b85+' also doesn't seem to load this SWC file, which may be important information for the reconstructors - however, it's beside the point now.

**Comment by wizmer** [comment] 2020-12-02 16:25
Hum, interesting. Yes, I think that the problem is what you are mentioning. 
I was able to open the morphology you sent with morphio. Can you try with NeuroM v2 (which uses morphio as a backend) and see if it works ?
All you need is to reinstall neurom with the `--pre` option.
```bash
pip install --pre neurom
```
Thanks

**Comment by wizmer** [comment] 2020-12-02 16:36
Alternatively you can use morph-tool to "rewrite" the morphologies in the same format:
```bash
pip install morph-tool
morph-tool convert folder -ext swc INPUTDIR OUTPUTDIR
```
It will re-write the files to swc but with a decent ordering

**Comment by jonathanlurie** [comment] 2020-12-02 17:18
Hey, thanks for the responsiveness! I manage to open the file with MorphIO si it should be fine with the NeuroM that uses it as a backend. I'll keep you updated!

**Comment by mgeplf** [comment] 2020-12-03 07:29
Here is a reduced/anonymized test case:
```
##n type x y z r parent
1   1   1   1   1 1 -1
99  3  99  99  99 1 100
100 3 100 100 100 1 101
101 3 101 101 101 1 102
102 3 102 102 102 1 103
103 3 103 103 103 1 104
104 3 104 104 104 1 105
105 3 105 105 105 1 106
106 3 106 106 106 1 107
107 3 107 107 107 1 108
108 3 108 108 108 1 1
```

**Comment by asanin-epfl** [comment] 2021-04-29 14:32
Closing as it has been solved in NeuroM v2

**Closed by asanin-epfl** 2021-04-29 14:32 UTC
