### ISSUE TITLE
neurolucida: No handlers could be found for logger

### ISSUE THREAD

**Issue by juanchopanza** [BlueBrain/NeuroM#362] opened 2016-06-02 08:53 UTC
`neurolucida` tries to write to a logger, and when there isn't one, this message appears:

> No handlers could be found for logger "neurom.io.neurolucida"

To reproduce:

``` python
from neurom import fst
nrn = fst.load_neuron('test_data/neurolucida/bio_neuron-001.asc')
```

**Comment by lidakanari** [comment] 2016-06-03 09:33
I don't think that this issue is fixed! Here's the last git pull I did:

```
commit fe2a5c8ac40dfb791e09731cc9589b8136dd3cba
Merge: 2603c7f 8b89302
Author: Juan Palacios <juan.palacios.puyana@gmail.com>
Date:   Thu Jun 2 23:06:26 2016 +0200

    Merge pull request #363 from juanchopanza/master
    
    Add neurom.log module with default stream logger
```

But the problem persists:
```python
from neurom import fst

nrn = fst.load_neuron('test_data/neurolucida/bio_neuron-001.asc')

neurom/io/neurolucida.py:254: UserWarning: This is an experimental reader. There are no guarantees regarding ability to parse Neurolucida .asc files or correctness of output.
  warnings.warn(msg)
No handlers could be found for logger "neurom.io.neurolucida"

```

**Comment by juanchopanza** [comment] 2016-06-03 10:14
You need to import the `neurom.log` module to get the handler.

```python
from neurom import log
from neurom import fst
nrn = fst.load_neuron('test_data/neurolucida/bio_neuron-001.asc')
```

But if you don't do that, at least now you get a warning telling you not to trust the reader :-)

**Comment by eleftherioszisis** [comment] 2016-06-04 12:25
I have a question. If the ```log``` is not imported, the file will be loaded correctly?

I am asking because a user will not know that he has to load the log, which he is not going to use, in order for the ```load_neuron``` function to properly work.

**Comment by juanchopanza** [comment] 2016-06-04 15:23
What file? `load_neuron` behaves as "correctly" as it can for `.asc` files, that is to say, kind of maybe a little bit. The issue is that the user wasn't being warned before, and now they are.

**Comment by eleftherioszisis** [comment] 2016-06-04 16:02
Ok, I was wondering if there was a difference in loading process or possible error that could be generated by not loading the logger.

**Comment by wvangeit** [comment] 2019-02-19 09:52
I can still reproduce this on the latest version of NeuroM on PyPi.

**Comment by wizmer** [comment] 2019-02-20 07:34
What can you reproduce exactly ? Simply opening a neuron does not trigger any message for me.

**Comment by wvangeit** [comment] 2019-02-20 08:09
Mmm, yes indeed. If I just open 1 morphology it doesn't happen. It only happens in the diameter-check scripts when processing an entire set. Maybe it only happens when a problems in the morphology occurs ? 
Don't have much time to investigate at the moment. You can close it again if you want, will reopen if I can give a small reproducible example.

**Comment by mgeplf** [comment] 2019-02-20 08:42
It depends on whether you have logging enabled, and if you're on python 2.7 - python 3.x handles this better when a logging.warning is being raised.

The 'correct' solution is to have a logger setup by the calling application:
```
import logging
logging.basicConfig()
```

Since this is a library, I'm reluctant to work around it by mucking with the logging internals.  I can do it if people think it's preferable than the message that one should turn on logging (although, the message is less than stellar in that regard)

**Comment by genric** [comment] 2019-02-20 09:08
Wouldn't this help: https://docs.python-guide.org/writing/logging/#logging-in-a-library ?

**Comment by mgeplf** [comment] 2019-02-20 09:14
Cool, didn't know about that trick, I will look into it.  Thanks.

**Closed** 2019-02-28 10:29 UTC

**Comment by wvangeit** [comment] 2019-02-28 14:37
Thanks 👍
