### ISSUE TITLE
morph_stats fails in python3.5

### ISSUE THREAD

**Issue by lsqshr** [BlueBrain/NeuroM#555] opened 2016-11-29 11:00 UTC
When I run morph_stats with python3.5, it complained that 'map' cannot be dumped in json as below

```
Traceback (most recent call last):
  File "morph_stats", line 141, in <module>
    main(_args)
  File "morph_stats", line 114, in main
    print(json.dumps(results, indent=2, separators=(',', ':')))
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 200, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <map object at 0x7f0916cd13c8> is not JSON serializable
siqi@siqi-Alienware-14:~/NeuroM/apps$ python3 morph_stats ~/Desktop/AK11N1.CNG.swc 
Traceback (most recent call last):
  File "morph_stats", line 141, in <module>
    main(_args)
  File "morph_stats", line 114, in main
    print(json.dumps(results, indent=2, separators=(',', ':')))
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 200, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <map object at 0x7fcc8d282588> is not JSON serializable
```

To reproduce this bug, try a random [swc](http://neuromorpho.org/dableFiles/cameron/CNG%20version/AK11N1.CNG.swc) from NeuroMorpho. 

To ensure I was using python3: 
```
python3 apps/morph_stats ~/Desktop/AK11N1.CNG.swc
```

**Comment by mgeplf** [comment] 2016-11-29 11:49
Thanks, I can reproduce this.  I will have a look at this later today or tomorrow.

**Comment by mgeplf** [comment] 2016-11-29 12:21
Ok, so the root cause is that np.array(iterable) doesn't actually create the array from a map() function, now that map() is lazy.

ex:
```
In [1]: from itertools import imap
In [2]: import numpy as np
In [3]: it = imap(lambda x: x, range(10))

In [4]: type(it)
Out[4]: itertools.imap

In [5]: np.array(it)
Out[5]: array(<itertools.imap object at 0x7f0106e1a490>, dtype=object)

In [6]: asdf = np.array(it)

In [7]: np.max(asdf)
Out[7]: <itertools.imap at 0x7f0106e1a490>
```

In other words, np.array() is creating a single element array with the iterator object in it.

I will have to investigate what the cleanest fix for this is.

**Comment by lsqshr** [comment] 2016-11-29 22:59
Great!. I have closed #554 and will be waiting for a neater fix.

**Comment by mgeplf** [comment] 2016-12-01 08:55
It might take a few days, as I'm in the middle of removing the deprecated point_neuron code, which I need to get done first...

**Comment by mgeplf** [comment] 2016-12-07 09:11
Can you try with the latest version? I believe it should work now

**Comment by lsqshr** [comment] 2016-12-08 00:00
@mgeplf I tried with the forward master on python3.5 with the swc at the top of this issue and got the error below:
```
(neurom-env) $ python3 apps/morph_stats /home/siqi/Downloads/test1.swc
Traceback (most recent call last):
  File "apps/morph_stats", line 142, in <module>
    main(_args)
  File "apps/morph_stats", line 103, in main
    results[path] = extract_stats(nm.load_neuron(path), config)
  File "/home/siqi/repo/NeuroM/neurom/apps/morph_stats.py", line 82, in extract_stats
    assert stat.shape in ((), (3, ), ), \
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by mgeplf** [comment] 2016-12-12 12:06
Ok, that should be fixed now if you try the master.  Sorry about that.

**Comment by mgeplf** [comment] 2016-12-13 15:19
@lsqshr Do you mind trying it again?

**Comment by lsqshr** [comment] 2016-12-14 00:07
Hi @mgeplf, I can confirm the bug is fixed! Thanks a lot!

**Closed** 2016-12-14 00:07 UTC

**Comment by mgeplf** [comment] 2016-12-14 08:02
Excellent.  If you find any other problems, don't hesitate to open more issues.  Thanks for your help.

**Comment by lsqshr** [comment] 2016-12-14 08:32
Definitely!
